# Generated by Django 3.0.7 on 2020-06-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('CM', 'Crypto Mining'), ('S', 'Stock'), ('M', 'Market'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
