# Generated by Django 3.0.7 on 2020-07-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
    ]
